### GET Section by ID
GET http://localhost:4321/api/sites/my-site/sections
Accept: application/json



### PUT Update Section
PUT http://localhost:4321/api/sections/1
Content-Type: application/json

{
    "title": "Updated Section Title",
    "html": "<p>Updated HTML</p>",
    "css": "body { background: black; }",
    "js": "console.log('Updated JS');",
    "contents": [
        {
            "langCode": "en",
            "content": { "text": "Updated English Content" }
        },
        {
            "langCode": "de",
            "content": { "text": "Aktualisierter deutscher Inhalt" }
        }
    ]
}


